/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-09-02 06:37:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1736445488275L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1736445488278L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>Tea and Meal - Free CSS Template</title>\n");
      out.write("<meta name=\"keywords\" content=\"\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>Food System</title>\n");
      out.write("<meta name=\"keywords\" content=\"\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");

	String uEmail=(String)session.getAttribute("uEmail");
	String aEmail=(String)session.getAttribute("aEmail");

      out.write("\n");
      out.write("	<div id=\"templatemo_container\">\n");
      out.write("		<div id=\"templatemo_header\">\n");
      out.write("			<div id=\"site_title\"></div>\n");
      out.write("		</div>\n");
      out.write("		<!-- end of header -->\n");
      out.write("\n");
      out.write("		<div id=\"templatemo_menu\">\n");
      out.write("		");
if (uEmail==null && aEmail==null){ 
      out.write("\n");
      out.write("			<ul>\n");
      out.write("				<li><a href=\"index.jsp\"><b>Home</b></a></li>\n");
      out.write("				<li><a href=\"food\"><b>FoodMenu</b></a></li>\n");
      out.write("				<li><a href=\"addCustomer.jsp\"><b>Registration</b></a></li>\n");
      out.write("				<li><a href=\"login.jsp\"><b>Login</b></a></li>\n");
      out.write("				<li><a href=\"contactUs\"><b>Contact Us</b></a></li>\n");
      out.write("			</ul>\n");
      out.write("		");
}
      out.write('\n');
      out.write('	');
      out.write('	');
if(uEmail==null && aEmail!=null){ 
      out.write("\n");
      out.write("			<ul>\n");
      out.write("				<li><a href=\"index.jsp\"><b>Home</b></a></li>\n");
      out.write("				<li><a href=\"food\"><b>Menu</b></a></li>\n");
      out.write("				<li><a href=\"AddFood.jsp\"><b>AddFood</b></a></li>\n");
      out.write("				<li><a href=\"customer\"><b>Customers</b></a></li>\n");
      out.write("				<li><a href=\"feedback\"><b>FeedBack</b></a></li>\n");
      out.write("				<li><a href=\"changepass.jsp\"><b>Edit</b></a></li>\n");
      out.write("				<li><a href=\"login\"><b>Logout</b></a></li>\n");
      out.write("			</ul>	\n");
      out.write("		");
}
      out.write('\n');
      out.write('	');
      out.write('	');
if(uEmail!=null && aEmail==null){ 
      out.write("\n");
      out.write("			<ul>\n");
      out.write("				<li><a href=\"index.jsp\"><b>Home</b></a></li>\n");
      out.write("				<li><a href=\"food\"><b>Menu</b></a></li>\n");
      out.write("				<li><a href=\"cart\"><b>View Cart</b></a></li>\n");
      out.write("				<li><a href=\"addFeedBack.jsp\"><b>FeedBack</b></a></li>\n");
      out.write("				<li><a href=\"changepass.jsp\"><b>Edit</b></a></li>\n");
      out.write("				<li><a href=\"contactUs.jsp\"><b>Contact us</b></a></li>\n");
      out.write("				<li><a href=\"login\"><b>Logout</b></a></li>\n");
      out.write("			</ul>	\n");
      out.write("		");
 }
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<div id=\"templatemo_top_dishes\">\n");
      out.write("\n");
      out.write("			<h1>Recommended Dishes</h1>\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/Idli.jpeg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\" />\n");
      out.write("				<h2>Idli Sambar</h2>\n");
      out.write("				<p>\n");
      out.write("					lentils, plenty of spices, mixed vegetables and herbs <a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/PavBhaji.jpg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\"/>\n");
      out.write("				<h2>Pav Bhaji</h2>\n");
      out.write("				<p>\n");
      out.write("					Chillies,Capsicum,Turmeric,Salt, Coriander Whole, \n");
      out.write("					 <a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/PaniPuri.jpg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\" />\n");
      out.write("				<h2>Pani Puri</h2>\n");
      out.write("				<p>\n");
      out.write("					 potatoes,spiced water,chutneys,onions,sev.\n");
      out.write("					 <a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/Burger.jpg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\"/>\n");
      out.write("				<h2>Burger</h2>\n");
      out.write("				<p>\n");
      out.write("					fresh lettuce,tomato,onions,Cheese. \n");
      out.write("					<a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/Alu_Vadi.jpg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\" />\n");
      out.write("				<h2>Alu Vadi</h2>\n");
      out.write("				<p>\n");
      out.write("					Rice flour,Red chili powder,Turmeric powder,Salt,\n");
      out.write("					Tamarind Jaggery Pulp <a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/PuranPoli.jpg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\" />\n");
      out.write("				<h2>Puran Poli</h2>\n");
      out.write("				<p>\n");
      out.write("					flour/maida, lentils, jaggery and cardamoms <a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/Pizza.jpg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\" />\n");
      out.write("				<h2>Pizza</h2>\n");
      out.write("				<p>\n");
      out.write("					Tomatoes,oil,anchovies,garlic,mozzarella cheese <a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div class=\"top_dishes_box\">\n");
      out.write("				<img src=\"images/Sandwhich.jpg\" alt=\"image\" width=\"205\"\n");
      out.write("					height=\"150\" />\n");
      out.write("				<h2>Sandwhich</h2>\n");
      out.write("				<p>\n");
      out.write("					bread(toasted or untoasted),sliced cheese, vegetable fillings \n");
      out.write("					(lettuce, tomato, onion, etc.). <a href=\"#\">Read more...</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"cleaner\">&nbsp;</div>\n");
      out.write("		</div>\n");
      out.write("   ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>Tea and Meal - Free CSS Template</title>\n");
      out.write("<meta name=\"keywords\" content=\"\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div id=\"templatemo_content\">\n");
      out.write("			<span class=\"top\"></span>\n");
      out.write("			<div id=\"templatemo_innter_content\">\n");
      out.write("\n");
      out.write("				<div id=\"templatemo_content_left\">\n");
      out.write("					<h1>Welcome to our website</h1>\n");
      out.write("					<img src=\"images/PavBhaji.jpg\" alt=\"image\" width=\"300\"\n");
      out.write("						height=\"200\" />\n");
      out.write("\n");
      out.write("					<p>Donec malesuada elit vel enim. Lorem ipsum dolor sit amet,\n");
      out.write("						consectetur adipiscing elit. Suspendisse id velit elementum mi\n");
      out.write("						egestas ullamcorper. Vivamus nec dui.</p>\n");
      out.write("					<p>Suspendisse vitae nibh ac nunc mattis blandit. Morbi\n");
      out.write("						consectetur ullamcorper felis. Nulla nec elit. Aliquam et mauris.\n");
      out.write("						Ut euismod congue diam.</p>\n");
      out.write("					<a href=\"#\">Read more...</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"cleaner_with_height\">&nbsp;</div>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<!-- end of content left -->\n");
      out.write("\n");
      out.write("				<div id=\"templatemo_content_right\">\n");
      out.write("					<h1>What's new?</h1>\n");
      out.write("					<div class=\"right_column_section\">\n");
      out.write("						<h2>Special meal for you</h2>\n");
      out.write("						<img src=\"images/Alu_Vadi.jpg\" alt=\"image\" width=\"250\"\n");
      out.write("						height=\"200\"/>\n");
      out.write("						<p>Curabitur turpis. Nulla a risus. Aliquam lectus dui,\n");
      out.write("							euismod id, volutpat ac, fringilla eu, ipsum.</p>\n");
      out.write("						<a href=\"#\">Read more...</a>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<!-- end of content right -->\n");
      out.write("				<div class=\"cleaner\">&nbsp;</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"cleaner\" style=\"background: #fff;\">&nbsp;</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<div id=\"templatemo_footer\">\n");
      out.write("\n");
      out.write("			<a href=\"#\">Home</a> | <a href=\"#\">Tea</a> | <a href=\"#\">Top\n");
      out.write("				Dishes</a> | <a href=\"#\">Company</a> | <a href=\"#\">FAQs</a> | <a\n");
      out.write("				href=\"#\">Contact Us</a><br /> Copyright © 2024 <a href=\"#\"><strong>Your\n");
      out.write("					Company Name</strong></a>\n");
      out.write("			<!-- Credit: www.templatemo.com -->\n");
      out.write("		</div>\n");
      out.write("		<!-- end of footer -->\n");
      out.write("		<!--  Free CSS Templates by TemplateMo.com  -->\n");
      out.write("	</div>\n");
      out.write("	<!-- end of container -->\n");
      out.write("	<!-- templatemo 082 tea and meal -->\n");
      out.write("	<!-- \n");
      out.write("Tea And Meal Template \n");
      out.write("http://www.templatemo.com/preview/templatemo_082_tea_and_meal \n");
      out.write("-->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
